server:
  port: 8201
spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://localhost:9411

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    url: jdbc:mysql://localhost:3306/tu_ling
    username: root
    password: root


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml


#  leaf.name=com.sankuai.leaf.opensource.test
#  leaf.segment.enable=false
#  #leaf.segment.url=
#  #leaf.segment.username=
#  #leaf.segment.password=
#
#  leaf.snowflake.enable=false
##leaf.snowflake.address=
##leaf.snowflake.port=

