server:
  port: 8080


spring:
  application:
    name: distribute-service
#  zipkin:
#    base-url: http://localhost:9411



#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8001/eureka/


leaf:
  name: com.sankuai.leaf.opensource.test\
  segment:
    enable: true
    url: jdbc:mysql://localhost:3306/leaf
    username: root
    password: root
  snowflake:
    enable: false
